Makefile, requirements.txt
Add a flake8 make target
r? @ajvb
=> Add flake8 make target

README.md, conftest.py, severity.conf.example, severity.py
=> severity config

.travis.yml, Makefile
refs #13 
Prep for running doctests.
=> reenable travis CI

.travis.yml
=> Run doctests from CI

service_report_generator.py
After making `-jo` into `--jo`, that changed the dest. Change it back to `json_out` / `markdown_out`.
=> Added dest param to add_arguement

aws/client.py, service_report_generator.py, severity.py
* Made BotocoreClient.extract_key docstring a doctest
* Fixed order dependence in doct tests
r? @g-k
=> Doctest improvements/fixes

severity.py
=> fix severity warning (allowing all whitespace not just tabs)

README.md, aws/client.py, conftest.py, exemptions.conf.example, exemptions.py, severity.py
Fixes #18 up to a per test name and ID level. 
The first two commits fix other doctests and other stuff.
r? @ajvb
=> Exemptions conf

pytest_wrapper.sh
Will make it easier to run it multiple times in one container run.
Also made some small bash style tweaks.
r? @g-k
=> Have pytest_wrapper.sh take AWS_PROFILE as arg

aws/client.py
Changes:
* Add more doctests for client methods
* Remove the `reify_response` fn. I did some testing and the same number of ec2 tests passed and failed with and without the call, so I think the change should be fine.
r? @ajvb
=> More tests

exemptions.py
=> Fix retrieval of exemptions when its a regex rule

aws/iam/test_iam_user_without_mfa.py
Current one is specific to "Admin" accounts.
r? @g-k
=> Add MFA on user with console access test

service_report_generator.py
Changes it from "sg-000000 my-secgroup" -> "my-secgroup".
r? @g-k
=> Fix secgroup resource name in csv

Makefile, aws/client.py, conftest.py, gcp/client.py, gcp/compute/helpers.py, gcp/compute/resources.py, gcp/compute/test_firewall_opens_all_ports_to_all.py, gcp/sql/resources.py, gcp/sql/test_sql_instance_automatic_backup_enabled.py, gcp/sql/test_sql_instance_ssl_required.py, requirements.txt
Initial GCP support with initial tests for Firewalls and CloudSQL instances.
r? @g-k
=> GCP Support

README.md
refs: https://github.com/mozilla-services/pytest-services/commit/401c88a and PR #100 
r? @ajvb
=> readme: rm --aws-regions; aws from --debug-calls

Makefile, README.md, bin/auth/setup_gsuite.py, config.yaml.example, conftest.py, custom_config.py, gsuite/admin/helpers.py, gsuite/admin/resources.py, gsuite/admin/test_admin_user_is_inactive.py, gsuite/client.py
This adds support for GSuite tests and adds the first test: `test_admin_user_is_inactive`.
r? @g-k
=> Initial GSuite test

aws/client.py
=> Warn when --aws-profiles doesn't match AWS_PROFILE

aws/iam/helpers.py, aws/iam/meta_test_resources.py, cache.py
=> fix unserializing datetimes from cache

conftest.py, meta_test_cache.py
the new meta test file was supposed to be in #140
=> Fix report json serialization errors

conftest.py
This fixes a deprecation around the use of `MarkInfo`:
```
pytest-services/conftest.py:199: RemovedInPytest4Warning:
MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
kwargs = ["...skipped..."] if marker.name == "parametrize" else marker.kwargs 
```
Note: Please don't merge till Jan 3rd or later.
=> Fix MarkInfo "RemovedInPytest4Warning" deprecation warning

conftest.py, gcp/bigquery/resources.py, gcp/bigquery/test_dataset_not_publicly_accessible.py, gcp/client.py
Tests whether a BigQuery dataset is publicly accessible.
=> Add BigQuery dataset iam policy test

conftest.py
* create GSuiteClient even with no args
* add gcp project id to metadata
=> conftest tweaks

setup.py
pytest-aws already say 0.1.0 and 0.2.0 releases https://github.com/mozilla-services/pytest-services/releases
=> bump version to 0.3.0 in setup.py

Makefile
=> Makefile should report non prod python versions

.circleci/config.yml, .dockerignore, Dockerfile, Makefile, README.md
refs: #302
Changes:
* Add a docker container based on debian buster slim
* update readme (NB: replaces old example output with a TODO) 
* adds CCI config to publish images as `mozilla/frost` (need to enable in CCI and add dockerhub creds)
r? @ajvb
=> Fix 302 containerize

.circleci/config.yml, Dockerfile
Tweak some syntax and don't try to run tests that will fail.
Fixes GH-316
=> Make circleci work

README.md, conftest.py
=> Dont err when cache disabled

requirements.txt
=> add oauth2client to requirements

aws/sns/resources.py, aws/sns/test_sns_topics_without_subscriptions.py
This test checks for SNS topics that lack any subscriptions.  Thanks @ajvb and @sven for assistance with the lambda.
r? @ajvb
=> Add a test for SNS Topics that have no subscriptions.

aws/rds/helpers.py, aws/rds/test_rds_db_snapshot_not_too_old.py
Similar to https://github.com/mozilla/frost/pull/382, this is to check a RDS snapshot is not too old.
Also I probably won't submit more tests for a while since we have decided to shift efforts to enabling tests.
=> Add an rds check

.travis.yml, docs/NewServices.rst
first draft -- please check for correctness.  [rendered view](https://hwine.github.io/frost/NewServices.html#add-service-specific-content)
=> [Doc] explain parametrization conventions

conftest.py
Report (by exception) if duplicate values are added, as that is almost
certainly not intended.
=> Change METADATA_KEYS to a set

MANIFEST.in, setup.py
=> Include requirements.txt in frost package

aws/client.py, aws/conftest.py
Type annotations should make it easier to make changes or detect breaking changes.
Might need to tweak or tighten some of the annotations from Any.
refs: #355
=> add type annotations to aws/{client,conftest}.py

frost/__init__.py
0.4.3 milestone is complete - https://github.com/mozilla/frost/milestone/2
=> bump version to 0.4.3

.travis.yml
Travis was not activating virtual env for a number of tests
=> Fix Travis-CI builds
