mozilla/frost

- aws/client.py
- aws/ec2/resources.py
- aws/ec2/test_ec2_ebs_volume_encrypted.py
- aws/iam/resources.py
- aws/iam/test_iam_admin_user_without_mfa.py
- aws/iam/test_iam_user_without_mfa.py
This PR adds two tests:
- test_ec2_ebs_volume_encrypted
- test_iam_admin_user_without_mfa
We will want to eventually change `test_iam_admin_user_without_mfa` to test for all users that can log in, but for now this is a nice scoping.
If you look at the `user_is_admin` function, there is a comment block above it:
```
```
Something I'd like to discuss is whether attempting to scope to the concept of an "Admin" via policies is ok for now or if this should get more flushed out at this point.
> Encrypted EBS Volumes and Admin Users MFA tests

- Makefile
- README.md
- aws/rds/helpers.py
- aws/rds/test_rds_db_instance_encrypted.py
- aws/rds/test_rds_db_instance_not_publicly_accessible_by_vpc_sg.py
- aws/rds/test_rds_db_security_group_does_not_grant_public_access.py
- aws/rds/test_rds_db_snapshot_encrypted.py
- aws/rds/test_rds_db_snapshot_not_publicly_accessible.py
Prep work for #13 
Moving them all to `helpers.py` was to not have to deal with doctest executing pytest decorators. Would get errors around `botocore_client` being a `None type` due to not having pytest set it up. Don't really want those decorators executing anyways.
> Move RDS helpers to helpers.py + add 'make doctests'

- Makefile
This was just something I had stashed, but I think it's OK to land.
r? @ajvb
> make: remove the venv as part of clean target

- README.md
- aws/ec2/helpers.py
- aws/ec2/resources.py
- aws/ec2/test_ec2_instance_has_required_tags.py
- conftest.py
refs: https://github.com/mozilla-services/foxsec/issues/381
Adds a test for required EC2 instance tags.
example usage and output:
```console
pytest --ignore pagerduty/ --ignore aws/s3 --ignore aws/rds --ignore aws/iam -s --aws-profiles cloudservices-aws-stage --aws-regions us-east-1 --aws-debug-calls --aws-require-tag Name --aws-require-tag Type --aws-require-tag App --aws-require-tag Stack -k test_ec2_instance_has_required_tags
...
_____________________________________________ test_ec2_instance_has_required_tags[i-0e537fff] ______________________________________________
ec2_instance = {'AmiLaunchIndex': 0, 'Architecture': 'x86_64', 'BlockDeviceMappings': [{'DeviceName': '/dev/sda1', 'Ebs': {'AttachTim...11:53+00:00', 'DeleteOnTermination': True, 'Status': 'attached', 'VolumeId': …
```
> aws: Add ec2 instance required tag name test

- aws/client.py
- aws/ec2/helpers.py
- aws/ec2/resources.py
- aws/ec2/test_ec2_instance_has_required_tags.py
- aws/ec2/test_ec2_security_group_in_use.py
- aws/iam/resources.py
- aws/iam/test_iam_admin_user_without_mfa.py
- aws/rds/helpers.py
- aws/rds/resources.py
- aws/rds/test_rds_db_instance_encrypted.py
- aws/rds/test_rds_db_instance_is_multiaz.py
- aws/rds/test_rds_db_instance_minor_version_updates_enabled.py
- aws/redshift/resources.py
- aws/s3/resources.py
- aws/s3/test_s3_bucket_cors_disabled.py
- aws/s3/test_s3_bucket_does_not_grant_all_principals_all_actions.py
- aws/s3/test_s3_bucket_logging_enabled.py
- conftest.py
- report_json_to_service_json.py
- service_json_to_markdown_report.py
Fix flake8 failures so CI is passing.
refs #13
r? @ajvb
> fix flake8 failures

- README.md
- aws/ec2/test_ec2_instance_has_required_tags.py
- conftest.py
refs https://github.com/mozilla-services/pytest-services/issues/31
I think this is slightly more ergonomic.
r? @ajvb
> use nargs for multi value args

- Makefile
Small makefile tweaks to follow new conventions
r? @g-k
> Have make targets follow new conventions

- conftest.py
Fixes `TypeError: object of type 'NoneType' has no len()` when either profiles/regions opts are missing.
r? @g-k
> Fix type error for when an opt is not passed

- aws/ec2/helpers.py
- aws/ec2/test_ec2_instance_has_required_tags.py
1. This allows for the current doctest setup to work.
2. With the merging of https://github.com/mozilla-services/pytest-services/pull/43, we are now using test's docstrings for the description.
r? @g-k
> Moved test_ec2_instance_has_required_tags logic to a helper

- Makefile
`--cache-clear` not needed as CI won't have any persistence of the cache.
> Add aws-sg make target and remove --cache-clear from awsci target

- Makefile
- pytest_wrapper.sh
* `make install` now sources venv before pip installing
* Have pytest_wrapper.sh source the venv itself
r? @g-k
> Small fixes for pytest_wrapper.sh/make install

- Makefile
- README.md
- aws/client.py
- conftest.py
- pagerduty/test_user_has_escalation_policy.py
Fixes #52 
Originally I wanted this to read from the cache but I got stuck thinking about #11 #12 and decided to have it always return empty lists.
If this lands I'll open an issue to have the PD client respect the offline flag (didn't know how to get the pytestconfig outside a fixture off the top of my head).
r? @ajvb
> offline mode

- README.md
Policy that can be thrown on a user to allow for running all pytest-services' AWS tests.
r? @g-k 
@g-k Also, do you agree/think that this is the right place to store this?
> Added default IAM policy for pytest-services

- Makefile
- aws/redshift/test_redshift_security_group_does_not_allow_all_ips_access.py
- conftest.py
- pytest_wrapper.sh
1. Add support for optional severity/exemptions config in
pytest_wrapper.sh
2. Add '--continue-on-collection-errors' to ci make targets
3. Default skip redshift sec groups test
4. Remove passing in --aws-profiles for make targets
5. Fix serializing fixtures error
In regards to #4 - within our CI workflow, it is significantly
cleaner to use AWS's env var flow than create an AWS credentials
file.
In regards to #5:
Fixtures contain the boto response which has a datetime
object in it, causing "TypeError: datetime.datetime()
is not JSON serializable" errors to be thrown. Since we
are not currently using the fixtures metadata, simply
remove it
r? @g-k
>  Further tweaks for CI workflow 

- aws/client.py
- aws/ec2/test_ec2_instance_has_required_tags.py
- conftest.py
- service_report_generator.py
* Skip test_ec2_instance_has_required_tags if
no tags were passed in.
* Provide a default of [] to --aws-require-tags
(else it errors)
* Move skipped from being a warn to being a pass.
* Improve type checking of item in extract_key
r? @g-k
> Few changes based on initial CI run

- aws/ec2/test_ec2_instance_has_required_tags.py
- aws/rds/test_rds_db_instance_is_postgres_with_invalid_certificate.py
- aws/rds/test_rds_db_instance_minor_version_updates_enabled.py
- aws/s3/test_s3_bucket_does_not_grant_all_principals_all_actions.py
- aws/s3/test_s3_bucket_no_world_acl.py
not a keyed parameter when called directly
docs: https://docs.pytest.org/en/latest/skipping.html#skipping-test-functions
> fix reason in pytest.skip() calls

- service_report_generator.py
Allows for the markdown report to be cleaner and more easily actionable.
r? @g-k
> Filter out INFO severity results from markdown report

- aws/redshift/resources.py
- aws/redshift/test_redshift_security_group_does_not_allow_all_ips_access.py
Instead of skipping the redshift test by default,
if there is an error (most likely due to using EC2-VPC)
the resources call will return an empty list. Pytest will
display this as a `skip`, which is what we would want.
The main thing this provides is that it will support both
EC2-VPC and EC2-Classic without any code/config changes.
Fixes #66
r? @g-k
> Provide error default for redshift secgroups

- aws/ec2/helpers.py
We may want to change this later, but for now, I'd like to not fail on ICMP being open in security groups.
r? @g-k
> Don't fail security group tests on ICMP

- aws/ec2/helpers.py
- aws/ec2/test_ec2_security_group_opens_specific_ports_to_all.py
Includes a test that mimics Trusted Advisor's "Specific Ports
Unrestricted" test, which checks if any security group has
any ports beside 80, 25, 443, or 465 exposed to the public
internet.
Fixes #76 
r? @g-k
> test_ec2_security_group_opens_specific_ports_to_all

- README.md
- exemptions.py
Adds the ability to prefix a test id with an asterisk
to enable substring matching.
refs #67 
r? @g-k
> Substring matching for exemptions test id's

- aws/ec2/helpers.py
- aws/ec2/test_ec2_security_group_opens_specific_ports_to_all.py
Removes smtp ports from
test_ec2_security_group_opens_specific_ports_to_all
> Remove port 25 and 465 from specific port test

- Makefile
- aws/ec2/test_ec2_security_group_opens_all_ports.py
- aws/ec2/test_ec2_security_group_opens_all_ports_to_all.py
- aws/ec2/test_ec2_security_group_opens_all_ports_to_self.py
- aws/ec2/test_ec2_security_group_opens_specific_ports_to_all.py
This changes aws/ec2/test_ec2_security_group_opens_* tests to only fail if they
are attached to a resource. It also takes test_ec2_security_group_in_use out of
the default runs defined as make targets.
r? @g-k
> Only test secgroups attached to resources

- conftest.py
- service_report_generator.py
I've been using a modified version of service_report_generator.py
to generate csv's to use within spreadsheets. This includes a cleaned
up version of that code to allow for this option.
Also includes:
* adding __pytest_meta to metadata so that we can get the region of the resource.
* change to the language of 'warn' - as it's only being actively used for exemptions atm.
r? @g-k
> Support csv output of service report

- README.md
- aws/ec2/helpers.py
- aws/ec2/test_ec2_instance_has_required_tags.py
- aws/ec2/test_ec2_security_group_opens_specific_ports_to_all.py
- config.yaml.example
- conftest.py
- custom_config.py
- exemptions.conf.example
- exemptions.py
- regressions.py
- requirements.txt
- service_report_generator.py
- severity.conf.example
- severity.py
This refactors the separate exemptions and severity config into a single big YAML config. It also adds the ability to mark regressions and have security group specific whitelisted ports (fixing #92).
(I have not finished the changes required to the `README.md`. Would prefer to wait for the initial review before finishing it up.)
r? @g-k - mind giving this an initial once over?
> Config refactor

- aws/ec2/resources.py
In the spirit of returning actionable results, lets not include anything stopped/terminated or security groups associated with them.
r? @g-k
> Only get running or pending ec2 instances

- README.md
- aws/iam/helpers.py
- aws/iam/test_iam_user_is_inactive.py
- config.yaml.example
- custom_config.py
- requirements.txt
`test_iam_user_is_inactive` will fail on users considered "inactive". What is considered inactive by default is "Hasn't used the account in over a year from when the test is run" and there is a default grace period of 1 week on new accounts (since they may not have used the account at all yet). Config supports years, months, and weeks for relative "time ago".
Fixes #98
r? @g-k
> test_iam_user_is_inactive with config support

- conftest.py
- gcp/client.py
- gcp/compute/resources.py
- gcp/iam/helpers.py
- gcp/iam/resources.py
- gcp/iam/test_service_account_key_is_old.py
- gcp/sql/resources.py
Adds the first IAM test, which tests whether service account keys
are older than 90 days. Refactored GCPClient to support IAM calls
as they function quite a bit differently from networking, compute,
and sql calls.
Also removed support for passing in multiple GCP project ids, as this is
a feature I have not found useful and makes the code a bit more complex.
r? @g-k
> Initial IAM test + refactor of GCPClient

- aws/client.py
- aws/cloudtrail/resources.py
- aws/cloudtrail/test_cloudtrail_enabled_in_all_regions.py
- aws/cloudtrail/test_cloudtrail_log_validation_enabled.py
- aws/ec2/resources.py
- aws/ec2/test_ec2_security_group_opens_all_ports.py
- aws/ec2/test_ec2_vpc_flow_log_enabled.py
- aws/elasticsearch/test_elasticsearch_domains_have_logging_enabled.py
This includes 4 new tests that are taken from prowler's
(https://github.com/toniblyx/prowler) set of "forensics-ready" tests.
These include 3 CIS Benchmark tests (2 for Cloudtrail and 1 for VPC Flow
Logs) and an additional test for logging being enabled on
ElasticSearchService Domains.
@g-k I would love your take on the current implementation of `test_cloudtrail_enabled_in_all_regions` and `test_ec2_vpc_flow_log_enabled`. I am doing a resource fetch within the test as I don't want these tests to not run if there are no cloudtrails or vpc flow logs. What do you think?
As well, tests are not passing due to the fact that `test_cloudtrail_enabled_in_all_regions` is tested on regions and there is a hardcoded list of `['us-east-1']` for when `--offline` is passed in. Will fix once I get the …
> Beginnings of implementing forensics-ready tests

- aws/iam/helpers.py
- aws/iam/resources.py
- aws/iam/test_iam_access_key_is_old.py
- config.yaml.example
- custom_config.py
test_iam_access_key_is_old tests whether an access key is
older than the configured expiration date with a default of a year.
r? @g-k
> Add test_iam_access_key_is_old with config options

- .travis.yml
- Makefile
- conftest.py
- heroku/client.py
- heroku/resources.py
- heroku/test_heroku_2fa.py
- requirements.txt
- Now follows pytest-services conventions
- doctests pass
- functional tests pass
Caching is not working. Phase 2 ;)
execution with valid org (failure expected):
```
$ pytest --tb line --organization mozillacorporation heroku/
===================================================================================================================== test session starts ======================================================================================================================
platform linux -- Python 3.6.4, pytest-3.3.2, py-1.5.3, pluggy-0.6.0
metadata: {'Python': '3.6.4', 'Platform': 'Linux-4.4.0-43-Microsoft-x86_64-with-debian-stretch-sid', 'Packages': {'pytest': '3.3.2', 'py': '1.5.3', 'pluggy': '0.6.0'}, 'Plugins': {'pudb': '0.6', 'metadata': '1.5.1', 'json': '0.4.0', 'html': …
```
> Add Heroku support, take 2

- .travis.yml
- Makefile
fixes: #119 
Add checks for the patterns in https://github.com/mozilla-services/pytest-services/issues/119#issuecomment-391153748
NB: This requires ripgrep which might not be installed in CI.
Functional Tests:
> Fix conftest imports

- aws/ec2/test_ec2_instance_running_required_amis.py
- config.yaml.example
- custom_config.py
Adds a test that will check that all running EC2 instances are using an
AMI in the "required_amis" list within the provided config file. If no AMIs
exist in this list, skip all of the tests.
r? @psiinon @g-k
> Add test_ec2_instance_running_required_amis test

- README.md
- aws/iam/resources.py
- config.yaml.example
- custom_config.py
Originally, a user was an "admin" if they had a policy that included the
word "admin" in it. That kinda worked sometimes, but needed to be
replaced.
Now, in the config file you can list the admin policies and groups and a
user or role will be matched against these lists.
This PR also updates the `config.yaml` example in the README.
> Fix the concept of "admin" in aws iam tests

- README.md
- conftest.py
- gcp/client.py
- gcp/compute/helpers.py
- gcp/compute/test_firewall_opens_all_ports_to_any.py
- gcp/compute/test_firewall_opens_any_ports_to_all.py
- gcp/iam/resources.py
- gcp/iam/test_admin_service_accounts.py
- gcp/sql/test_sql_instance_private_ip_required.py
- gcp/sql/test_sql_instance_ssl_required.py
Adds:
* `test_firewall_opens_all_ports_to_any`
* `test_firewall_opens_any_ports_to_all`
* `test_admin_service_accounts`
* `test_sql_instance_private_ip_required`
* Initial GCP docs in README
Improve:
* Fix error within conftest when no args are provided to pytest
* Add error message to `test_sql_instance_ssl_required`
> Initial pass on refreshing GCP tests

- config.yaml.example
- conftest.py
- custom_config.py
- gcp/client.py
- gcp/compute/resources.py
- gcp/compute/test_gke_version_up_to_date.py
- gcp/iam/test_only_allowed_org_accounts.py
- service_report_generator.py
Adds two new tests:
* test_only_allowed_org_accounts - Confirms that only approved domains/gsuites have access to projects (with a list of role exceptions, e.g. log viewer)
* test_gke_version_up_to_date - Confirms GKE Clusters master and node versions are in the list of valid versions.
Also adds basic support for GCP CSV reports via `service_report_generator.py`
> Add new gcp tests, update service_report_generator for gcp

- .pre-commit-config.yaml
- Makefile
- requirements.txt
Fixes #272
Goal is to reduce impact of differing versions of black between this repo's venv and developer tooling. We now use pre-commit to enforce consistency.
- pinning of black version moves from requirements.txt to .pre-commit-config.yaml.
- pre-commit is added to requirements.txt, and black removed
- makefile targets modified to ensure pre-commit init is run.
> Move black to pre-commit hook

- README.md
- aws/ec2/helpers.py
- aws/ec2/resources.py
- aws/ec2/test_ec2_ebs_snapshots_are_private.py
Adds a new test for publicly available EBS snapshots.
Docs/Reference:
https://techcrunch.com/2019/08/09/aws-ebs-cloud-backups-leak/
https://www.cloudconformity.com/conformity-rules/EBS/public-snapshots.html#
> Add test for publicly available ebs snapshots

- setup.py
refs: #26 #278 
It is not runneable from the pypi install (no python console or script). This is to have something to upload to reserve the name
setup.py sdist results in a 52K tgz file.
r? @ajvb
> add a setup.py

- aws/ec2/helpers.py
Currently, the tests that use these helpers are failing on security groups that allow for ICMP for IPv6. This fixes that by including `icmpv6` in the `icmp` filter check.
> Include ICMPv6 in security group filtering

- conftest.py
Include `InstanceId` in pytest results metadata.
The instance id tends to already be present as the "id" of the test, but this will make extracting it easier in a lot of cases.
> Include InstanceId in pytest metadata

- aws/elb/test_elb_instances_attached.py
Checks whether an ELB (v1) has any instances attached and fails if there are none. Similar to our "security group in use" test.
> Test for ELB with 0 instances attached

- .pre-commit-config.yaml
- .travis.yml
Run on Python 3.6+ in CI. Don't specify python version in pre-commit config.
Related to #304, #305, #306
> Test on multiple versions of python

- cache.py
fails with ImportError and we don't support Python 2
r? @ajvb
> cache: remove PY2 import from pytest internals

- aws/elb/resources.py
Getting ELB tags is it's own call. Call it for each ELB and load them in the "expect" location in the main ELB dict (key of `Tags`).
> Get associated tags for elbs

- .circleci/config.yml
- Makefile
'rg' isn't part of the base images, and may not be on some dev's
machines. So switch to the old standby of 'grep' -- with a bunch more
options for the same behavior.
> Replace use of 'rg' for CircleCI

- aws/ec2/helpers.py
- aws/ec2/resources.py
- aws/ec2/test_ec2_all_eips_bound.py
In the cloudops-dev account, this test actually finds more unbound IPs than bound IPs, and there are valid use cases for unbound IPs. This test may still be useful, and it was on our list of desired tests.
> Add test to verify that all EIPs are bound to instances.

- aws/elb/resources.py
- aws/elb/test_elb_desync_mode.py
- aws/elb/test_elb_instances_attached.py
Assuming https://docs.google.com/document/d/1yKLDxZ9S9N456ZPh4qEM0GY2DrMZqsqG69ByCSELjzE/edit is approved this PR adds a test to check whether ELBs are deployed in HTTP Desync strictest mode. I have a doctest for the test itself, but have not functional tested that the resources change fetches the right data. 
We would need to add exemptions for current ELBs, but shouldn't need to for new ELBs.
Alternatively, we could change this to a negative test to make sure we're not running in `monitor` mode anywhere and not add exemptions for existing services.
r? @ajvb 
cc @sciurus @jbuck
> elb: add test for http desync setting

- config.yaml.example
- custom_config.py
- gcp/compute/test_only_allowed_gke_versions.py
For assistance with new vulns like https://cloud.google.com/kubernetes-engine/docs/security-bulletins#gcp-2020-012
> Add test for checking specific versions of GKE

- gcp/compute/test_gke_version_up_to_date.py
Before, the test checked if the node version is in validNodeVersions. However, unlike the short validMasterVersions the list in validNodeVersions is very long and goes all the way back to k8s 1.6. Thus, right now this does not actually test that the node version is up-to-date.
I initially thought to just check that the node version matched the master version, but realized this is not a good idea since google doesn't upgrade clusters and nodes in lockstep.
Instead, I've changed the check to verify that the node version is in the list of valid master versions. That should ensure we're on a recent version and still pass in the gap between cluster and node upgrades.
I've been unable to test locally and raised that in svc-auditing.
> Ensure GKE nodes are on a recent rather than just a valid version

- .travis.yml
- Dockerfile
- Makefile
- README.md
- conftest.py
- frost/__init__.py
- frost/cli.py
- requirements.txt
- setup.py
refs #113 #302
Changes:
* Add a pypi package with CLI bin cmd `frost` ... it doesn't do anything
* subcommand `frost test` aliased to `pytest -s --debug-calls` run from the frost test root 
* subcommand `frost list` to print out test file paths (since we default to ignoring all of them)
* Update the readme to use the `frost` command instead of docker (we never published the docker image and would have to mount tests in)
* fix the `awsci` make target to run aws tests
NB: **running tests via `pytest` is unchanged**
Caveats:
* heroku tests are blocked on being able to install the package: https://github.com/hwine/python-herokuadmintools/issues/1
* the test files still live outside the frost package directory
This should:
* provide a single entrypoint independent of pytest for future …
> Fix 302 add cli bin

- README.md
- aws/client.py
- conftest.py
fixes: #348
functional tests:
```console
$ pytest --debug-cache --debug-calls -p 'no:cacheprovider' -s --aws-regions=us-east-1 --aws-profiles='default' aws/ec2/test_ec2_instance_has_required_tags.py
collecting ... calling AWSAPICall(profile='default', region='us-east-1', service='ec2', method='describe_instances', args=[], kwargs={'Filters': [{'Name': 'instance-state-name', 'Values': ['pending', 'running']}]})
...
$ pytest --debug-cache --debug-calls -p 'no:cacheprovider' -s --aws-regions=us-east-1,us-west-2 ...
...
collecting ... calling AWSAPICall(profile='default', region='us-east-1', service='ec2', method='describe_instances', args=[], kwargs={'Filters': [{'Name': 'instance-state-name', 'Values': ['pending', 'running']}]})
calling AWSAPICall(profile='default', region='us-west-2', …
```
> add --aws-regions cli arg

- conftest.py
- gcp/bigquery/resources.py
- gcp/client.py
- gcp/compute/resources.py
- gcp/compute/test_gke_version_up_to_date.py
- gcp/iam/resources.py
Reworks the GCP client, resources, and test code to add support for
passing in a Folder ID and running tests against all of the projects
within that folder.
Alongside that, this includes some stability fixes to the client code,
creates a new "frost" named cli arg group, and removes caching from the
GCP client.
Fixes #339 and #329
> Rework GCP code to support folder id arg

- .travis.yml
fixes: #344 
Add API token and username available on the master brach with permission to upload new frost packages to pypi as source and bdist wheels for tagged builds.
API token has name "frost-gh-travis-ci" unique ID c3a99f6b-abbc-4315-807a-276a7f103769 and belongs to https://pypi.org/user/mozfoxsec/
I don't have a way to functional test this before landing the change.
r? @ajvb @hwine
> ci: enable deploying tags to pypi

- README.md
- aws/ec2/helpers.py
- aws/ec2/test_ec2_security_group_opens_specific_ports_to_all.py
- config.yaml.example
- conftest.py
- custom_config.py
- gcp/compute/helpers.py
- gcp/compute/test_firewall_opens_any_ports_to_all.py
Adds support for allowed ports in GCP firewall tests
As well, switch from the term "whitelisted" to "allowed".
Note: Will require a change to all of the configs in our automation code.
> Support for allowed ports for GCP firewall tests

- gcp/client.py
- gcp/iam/resources.py
- gcp/iam/test_only_allowed_org_accounts.py
- service_report_generator.py
* Fix typo in `gcp.iam.resources.project_iam_bindings()`
* Add `deleted` variant to the service account filter for `test_only_allowed_org_accounts`
* s/pytest/frost/ in service report generator
> Small fixes for GCP and service report generator

- .travis.yml
- Makefile
- aws/client.py
- frost/cli.py
- gcp/iam/resources.py
and some little additional fixes
CI has been broken for doctests since the switch to using `frost test`
> Fix Frost exit codes

- frost/__init__.py
This is `0.4.1` with version bumped to `.2`   since .1 was already tagged.
> bump version to 0.4.2

- aws/client.py
- gcp/client.py
* Use directory struture for cache keys / filenames - Related to #349
* Use hashlib.md5 to hash args part of cache key for AWS - Fixes #349
* Get and use AWS account id if profile is None - Fixes #105
> Cache filename tweaks

- aws/iam/helpers.py
- aws/iam/resources.py
- aws/iam/test_iam_admin_user_without_mfa.py
- aws/iam/test_iam_user_without_mfa.py
- aws/rds/helpers.py
- aws/rds/resources.py
- aws/rds/test_rds_db_instance_not_publicly_accessible_by_vpc_sg.py
- aws/rds/test_rds_db_snapshot_not_publicly_accessible.py
- aws/s3/helpers.py
- aws/s3/test_s3_bucket_cors_disabled.py
- aws/s3/test_s3_bucket_does_not_grant_all_principals_all_actions.py
- aws/s3/test_s3_bucket_has_life_cycle_policy.py
- aws/s3/test_s3_bucket_logging_enabled.py
- aws/s3/test_s3_bucket_no_world_acl.py
- aws/s3/test_s3_bucket_versioning_enabled.py
- aws/s3/test_s3_bucket_versioning_mfa_delete_enabled.py
- aws/s3/test_s3_bucket_web_hosting_disabled.py
Fixes the `ids` argument in all `parameterize` calls that make use of `zip()` so that the outputted id is actually generated.
Fixes #412
> Make sure all test id's are reproducible

- Dockerfile
the original `COPY * ./` was actually copying sub-directories rather than the contents of the directory, so we want `COPY . /app`
Fixes #397
> Fixes COPY so that frost works as expected

- aws/sns/resources.py
- aws/sns/test_sns_pending_verified.py
- aws/sns/test_sns_subscriptions_without_topics.py
This PR intends to do two things:
1. Stop the `sns_subscription_attributes()` function from crashing the **test_sns_pending_verified.py** test when the AWS API throws an error on getting attributes for a subscription that does not have a parent topic.
1. Add a test to find subscriptions that have no parent topic.
It works as is, but there are few things that need fixing before a merge.
- The method used to truncate an SNS subscription ARN into an SNS topic ARN is not great:
```
topic = ':'.join(re.split(':', s_arn)[0:6])
```
- Several functions added might be moved into an SNS **helpers.py** file instead of their current location in **resources.py**.
- `sns_parent_topic_exists()`
- `sns_get_subscription_attrs()`
No doubt there are other pythonic issues.
> Add test for subscriptions without topics.

- .github/workflows/publish.yml
- .github/workflows/test.yml
refs: #429
Migrate CI to github actions
NB: test w/ python 3.9 fails due to a dep build failure, but I think that's fine for now and we can not require it to pass to merge
NB: there are third party actions for publish GH pages we could try too (pending GH admin approval)
I don't have a way to test the publish actions. I'm least certain about the `gh-pages` action in particular.
r? @ajvb @hwine
> add GHA CI

- .github/workflows/publish.yml
refs: #432
Two things:
* secrets with the `GITHUB_` are reserved, so I couldn't add `GITHUB_TOKEN`
* a new deploy key (with access limited to this repo; and accessible to any repo admin) seemed cleaner than generate a new repo scope oauth token, so I went that route
Next steps:
> ci: GHA clone with ssh deploy key
